# Generated by Django 5.0.6 on 2024-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
