# Generated by Django 5.0.6 on 2024-07-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='first_name',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='last_name',
            new_name='Title',
        ),
    ]
