# Generated by Django 5.0.6 on 2024-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_first_name_services_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Time',
            field=models.DateTimeField(default='2024-01-01T00:00:00'),
            preserve_default=False,
        ),
    ]
