# Generated by Django 5.0.6 on 2024-07-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_services_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Time',
        ),
    ]
