# Generated by Django 5.0.6 on 2024-07-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_services_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Blogs',
        ),
    ]
