# Generated by Django 5.0.6 on 2024-07-25 14:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_services_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
