# Generated by Django 5.0.6 on 2024-07-26 12:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_blogs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slugdata',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Title', unique=True),
        ),
    ]
