# Generated by Django 5.1.3 on 2024-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='created_at',
        ),
        migrations.AddField(
            model_name='letter',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
