# Generated by Django 5.0.6 on 2024-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
