# Generated by Django 5.0.6 on 2024-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
    ]
